# Generated by Django 5.1.6 on 2025-03-30 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0002_alter_organizationuser_organization"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organizationinventoryproduct",
            name="quantity",
        ),
        migrations.AlterField(
            model_name="organizationinventory",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventories",
                to="organization.organization",
            ),
        ),
        migrations.AlterField(
            model_name="organizationinventoryproduct",
            name="organization_inventory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="organization.organizationinventory",
            ),
        ),
    ]
