# Generated by Django 5.1.6 on 2025-03-31 19:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0003_remove_organizationinventoryproduct_quantity_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationProduct",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("PENDING", "Pending"),
                            ("DELETED", "Deleted"),
                        ],
                        default="ACTIVE",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity", models.IntegerField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("TABLETS", "Tablets"),
                            ("SYRUP", "Syrup"),
                            ("INJECTION", "Injection"),
                            ("OINTMENT", "Ointment"),
                            ("CAPSULE", "Capsule"),
                            ("NONE", "None"),
                        ],
                        default="NONE",
                        max_length=100,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organization.organization",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="organizationinventoryproduct",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="organization.organizationproduct",
            ),
        ),
    ]
