# Generated by Django 5.1.6 on 2025-03-31 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0004_organizationproduct_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationproduct",
            name="is_custom",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="organizationproduct",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="organizationproduct",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="organizationproduct",
            name="title",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="organizationproduct",
            name="type",
            field=models.CharField(
                choices=[
                    ("TABLETS", "Tablets"),
                    ("SYRUP", "Syrup"),
                    ("INJECTION", "Injection"),
                    ("OINTMENT", "Ointment"),
                    ("CAPSULE", "Capsule"),
                    ("NONE", "None"),
                ],
                default="NONE",
                max_length=10,
            ),
        ),
    ]
