# Generated by Django 5.1.6 on 2025-04-01 13:52

import shared.choices
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="delivery_status",
            field=models.TextField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PROCESSING", "Processing"),
                    ("ON_THE_WAY", "On The Way"),
                    ("COMPLETED", "Completed"),
                    ("CANCELED", "Canceled"),
                ],
                default="PENDING",
                verbose_name=shared.choices.DeliveryStatus,
            ),
        ),
    ]
