# Generated by Django 5.1.6 on 2025-03-11 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("OWNER", "Owner"),
                    ("MANAGER", "Manager"),
                    ("STAFF", "Staff"),
                    ("CUSTOMER", "Customer"),
                ],
                default="CUSTOMER",
                max_length=255,
            ),
        ),
    ]
