# Generated by Django 5.1.6 on 2025-03-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_orderitem_unit_price_alter_orderitem_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
